---
dist: bionic

language: python
python:
  - "3.8"

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main'
        key_url: 'https://apt.releases.hashicorp.com/gpg'
    update: true
    packages:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-bin
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - vagrant

install:
  - vagrant plugin install vagrant-libvirt
  - pip install wheel pyopenssl
  - pip install netaddr python-vagrant yamllint testinfra flake8
  - pip install ansible ansible-lint
  - pip install molecule molecule-vagrant python-vagrant
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script:
  - molecule test --scenario-name kvm
  - molecule test --scenario-name kvmsinglelv
  - molecule test --scenario-name kvmonlyvg
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
